### ISSUE TITLE
use tokens as translation key

### ISSUE THREAD

**Issue by breeswish** [vijos/vj4#90]
See http://docs.transifex.com/formats/yaml/

**Comment by breeswish** [comment]
The structure could be arranged as multiple levels similar to the directory and for pages it can be arranged by sections. For example:

```
components:
  navigation:
    items:
      home: '首页'
      problem: '题库'
      ...
  footer:
    sections:
      status:
        title: 状态
        items:
          queue: 评测队列
          status: 服务状态
      dev:
        title: 开发
        items:
          open_source: 开源
          api: API
      support:
        title: 支持
        items:
          help: 帮助
          blog: 博客
          qq_group: QQ 群
  dialog:
    login:
      ...
  pager:
    items:
      next_page: 下一页 ›
      last_page: 末页 »
      ...
  discussion:
    ...
  scratchpad:
    ...
  messagepad:
    ...
  ...
pages:
  problem_main:
    title: 题库
    sections:
      main:
        columns:
          problem: 题目
          submit: 递交数
          ac_rate: % AC
          difficulty: 难度
      stat:
        title: 统计

```
